// Implementation file for parser generated by fsyacc
module ExprPar
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "ExprPar.fsy"

  (* File Expr/ExprPar.fsy
     Parser specification for the simple expression language.
   *)

  open Absyn

# 14 "ExprPar.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | LPAR
  | RPAR
  | LBRA
  | RBRA
  | END
  | IN
  | LET
  | COMMA
  | PLUS
  | MINUS
  | TIMES
  | DIVIDE
  | EQ
  | MAX
  | NAME of (string)
  | CSTINT of (int)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_LPAR
    | TOKEN_RPAR
    | TOKEN_LBRA
    | TOKEN_RBRA
    | TOKEN_END
    | TOKEN_IN
    | TOKEN_LET
    | TOKEN_COMMA
    | TOKEN_PLUS
    | TOKEN_MINUS
    | TOKEN_TIMES
    | TOKEN_DIVIDE
    | TOKEN_EQ
    | TOKEN_MAX
    | TOKEN_NAME
    | TOKEN_CSTINT
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startMain
    | NONTERM_Main
    | NONTERM_Expr

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | LPAR  -> 1 
  | RPAR  -> 2 
  | LBRA  -> 3 
  | RBRA  -> 4 
  | END  -> 5 
  | IN  -> 6 
  | LET  -> 7 
  | COMMA  -> 8 
  | PLUS  -> 9 
  | MINUS  -> 10 
  | TIMES  -> 11 
  | DIVIDE  -> 12 
  | EQ  -> 13 
  | MAX  -> 14 
  | NAME _ -> 15 
  | CSTINT _ -> 16 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_LPAR 
  | 2 -> TOKEN_RPAR 
  | 3 -> TOKEN_LBRA 
  | 4 -> TOKEN_RBRA 
  | 5 -> TOKEN_END 
  | 6 -> TOKEN_IN 
  | 7 -> TOKEN_LET 
  | 8 -> TOKEN_COMMA 
  | 9 -> TOKEN_PLUS 
  | 10 -> TOKEN_MINUS 
  | 11 -> TOKEN_TIMES 
  | 12 -> TOKEN_DIVIDE 
  | 13 -> TOKEN_EQ 
  | 14 -> TOKEN_MAX 
  | 15 -> TOKEN_NAME 
  | 16 -> TOKEN_CSTINT 
  | 19 -> TOKEN_end_of_input
  | 17 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startMain 
    | 1 -> NONTERM_Main 
    | 2 -> NONTERM_Expr 
    | 3 -> NONTERM_Expr 
    | 4 -> NONTERM_Expr 
    | 5 -> NONTERM_Expr 
    | 6 -> NONTERM_Expr 
    | 7 -> NONTERM_Expr 
    | 8 -> NONTERM_Expr 
    | 9 -> NONTERM_Expr 
    | 10 -> NONTERM_Expr 
    | 11 -> NONTERM_Expr 
    | 12 -> NONTERM_Expr 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 19 
let _fsyacc_tagOfErrorTerminal = 17

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | LPAR  -> "LPAR" 
  | RPAR  -> "RPAR" 
  | LBRA  -> "LBRA" 
  | RBRA  -> "RBRA" 
  | END  -> "END" 
  | IN  -> "IN" 
  | LET  -> "LET" 
  | COMMA  -> "COMMA" 
  | PLUS  -> "PLUS" 
  | MINUS  -> "MINUS" 
  | TIMES  -> "TIMES" 
  | DIVIDE  -> "DIVIDE" 
  | EQ  -> "EQ" 
  | MAX  -> "MAX" 
  | NAME _ -> "NAME" 
  | CSTINT _ -> "CSTINT" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | LPAR  -> (null : System.Object) 
  | RPAR  -> (null : System.Object) 
  | LBRA  -> (null : System.Object) 
  | RBRA  -> (null : System.Object) 
  | END  -> (null : System.Object) 
  | IN  -> (null : System.Object) 
  | LET  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | TIMES  -> (null : System.Object) 
  | DIVIDE  -> (null : System.Object) 
  | EQ  -> (null : System.Object) 
  | MAX  -> (null : System.Object) 
  | NAME _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | CSTINT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us;65535us;1us;65535us;0us;1us;11us;65535us;0us;2us;8us;9us;11us;12us;16us;17us;18us;19us;22us;23us;24us;25us;31us;27us;32us;28us;33us;29us;34us;30us;|]
let _fsyacc_sparseGotoTableRowOffsets = [|0us;1us;3us;|]
let _fsyacc_stateToProdIdxsTableElements = [| 1us;0us;1us;0us;5us;1us;9us;10us;11us;12us;1us;1us;1us;2us;1us;3us;1us;4us;1us;4us;1us;5us;5us;5us;9us;10us;11us;12us;1us;5us;1us;6us;5us;6us;9us;10us;11us;12us;1us;6us;1us;7us;1us;7us;1us;7us;5us;7us;9us;10us;11us;12us;1us;7us;5us;7us;9us;10us;11us;12us;1us;7us;1us;8us;1us;8us;5us;8us;9us;10us;11us;12us;1us;8us;5us;8us;9us;10us;11us;12us;1us;8us;5us;9us;9us;10us;11us;12us;5us;9us;10us;10us;11us;12us;5us;9us;10us;11us;11us;12us;5us;9us;10us;11us;12us;12us;1us;9us;1us;10us;1us;11us;1us;12us;|]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us;2us;4us;10us;12us;14us;16us;18us;20us;22us;28us;30us;32us;38us;40us;42us;44us;46us;52us;54us;60us;62us;64us;66us;72us;74us;80us;82us;88us;94us;100us;106us;108us;110us;112us;|]
let _fsyacc_action_rows = 35
let _fsyacc_actionTableElements = [|7us;32768us;1us;8us;3us;11us;7us;14us;10us;6us;14us;21us;15us;4us;16us;5us;0us;49152us;5us;32768us;0us;3us;9us;33us;10us;34us;11us;32us;12us;31us;0us;16385us;0us;16386us;0us;16387us;1us;32768us;16us;7us;0us;16388us;7us;32768us;1us;8us;3us;11us;7us;14us;10us;6us;14us;21us;15us;4us;16us;5us;5us;32768us;2us;10us;9us;33us;10us;34us;11us;32us;12us;31us;0us;16389us;7us;32768us;1us;8us;3us;11us;7us;14us;10us;6us;14us;21us;15us;4us;16us;5us;5us;32768us;4us;13us;9us;33us;10us;34us;11us;32us;12us;31us;0us;16390us;1us;32768us;15us;15us;1us;32768us;13us;16us;7us;32768us;1us;8us;3us;11us;7us;14us;10us;6us;14us;21us;15us;4us;16us;5us;5us;32768us;6us;18us;9us;33us;10us;34us;11us;32us;12us;31us;7us;32768us;1us;8us;3us;11us;7us;14us;10us;6us;14us;21us;15us;4us;16us;5us;5us;32768us;5us;20us;9us;33us;10us;34us;11us;32us;12us;31us;0us;16391us;1us;32768us;1us;22us;7us;32768us;1us;8us;3us;11us;7us;14us;10us;6us;14us;21us;15us;4us;16us;5us;5us;32768us;8us;24us;9us;33us;10us;34us;11us;32us;12us;31us;7us;32768us;1us;8us;3us;11us;7us;14us;10us;6us;14us;21us;15us;4us;16us;5us;5us;32768us;2us;26us;9us;33us;10us;34us;11us;32us;12us;31us;0us;16392us;4us;16393us;9us;33us;10us;34us;11us;32us;12us;31us;1us;16394us;12us;31us;2us;16395us;11us;32us;12us;31us;2us;16396us;11us;32us;12us;31us;7us;32768us;1us;8us;3us;11us;7us;14us;10us;6us;14us;21us;15us;4us;16us;5us;7us;32768us;1us;8us;3us;11us;7us;14us;10us;6us;14us;21us;15us;4us;16us;5us;7us;32768us;1us;8us;3us;11us;7us;14us;10us;6us;14us;21us;15us;4us;16us;5us;7us;32768us;1us;8us;3us;11us;7us;14us;10us;6us;14us;21us;15us;4us;16us;5us;|]
let _fsyacc_actionTableRowOffsets = [|0us;8us;9us;15us;16us;17us;18us;20us;21us;29us;35us;36us;44us;50us;51us;53us;55us;63us;69us;77us;83us;84us;86us;94us;100us;108us;114us;115us;120us;122us;125us;128us;136us;144us;152us;|]
let _fsyacc_reductionSymbolCounts = [|1us;2us;1us;1us;2us;3us;3us;7us;6us;3us;3us;3us;3us;|]
let _fsyacc_productionToNonTerminalTable = [|0us;1us;2us;2us;2us;2us;2us;2us;2us;2us;2us;2us;2us;|]
let _fsyacc_immediateActions = [|65535us;49152us;65535us;16385us;16386us;16387us;65535us;16388us;65535us;65535us;16389us;65535us;65535us;16390us;65535us;65535us;65535us;65535us;65535us;65535us;16391us;65535us;65535us;65535us;65535us;65535us;16392us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;|]
let _fsyacc_reductions = lazy [|
# 179 "ExprPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> Absyn.expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : 'gentype__startMain));
# 188 "ExprPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 25 "ExprPar.fsy"
                                                               _1                
                   )
# 25 "ExprPar.fsy"
                 : Absyn.expr));
# 199 "ExprPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "ExprPar.fsy"
                                                               Var _1              
                   )
# 29 "ExprPar.fsy"
                 : 'gentype_Expr));
# 210 "ExprPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> int in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "ExprPar.fsy"
                                                               CstI _1             
                   )
# 30 "ExprPar.fsy"
                 : 'gentype_Expr));
# 221 "ExprPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> int in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 31 "ExprPar.fsy"
                                                               CstI (- _2)         
                   )
# 31 "ExprPar.fsy"
                 : 'gentype_Expr));
# 232 "ExprPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 "ExprPar.fsy"
                                                               _2                  
                   )
# 32 "ExprPar.fsy"
                 : 'gentype_Expr));
# 243 "ExprPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "ExprPar.fsy"
                                                               _2                  
                   )
# 33 "ExprPar.fsy"
                 : 'gentype_Expr));
# 254 "ExprPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> string in
            let _4 = parseState.GetInput(4) :?> 'gentype_Expr in
            let _6 = parseState.GetInput(6) :?> 'gentype_Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "ExprPar.fsy"
                                                               Let(_2, _4, _6)     
                   )
# 34 "ExprPar.fsy"
                 : 'gentype_Expr));
# 267 "ExprPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _3 = parseState.GetInput(3) :?> 'gentype_Expr in
            let _5 = parseState.GetInput(5) :?> 'gentype_Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "ExprPar.fsy"
                                                               Prim("max", _3, _5) 
                   )
# 35 "ExprPar.fsy"
                 : 'gentype_Expr));
# 279 "ExprPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_Expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "ExprPar.fsy"
                                                               Prim("/", _1, _3)   
                   )
# 36 "ExprPar.fsy"
                 : 'gentype_Expr));
# 291 "ExprPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_Expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "ExprPar.fsy"
                                                               Prim("*", _1, _3)   
                   )
# 37 "ExprPar.fsy"
                 : 'gentype_Expr));
# 303 "ExprPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_Expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "ExprPar.fsy"
                                                               Prim("+", _1, _3)   
                   )
# 38 "ExprPar.fsy"
                 : 'gentype_Expr));
# 315 "ExprPar.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_Expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "ExprPar.fsy"
                                                               Prim("-", _1, _3)   
                   )
# 39 "ExprPar.fsy"
                 : 'gentype_Expr));
|]
# 328 "ExprPar.fs"
let tables : FSharp.Text.Parsing.Tables<_> = 
  { reductions = _fsyacc_reductions.Value;
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 20;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = tables.Interpret(lexer, lexbuf, startState)
let Main lexer lexbuf : Absyn.expr =
    engine lexer lexbuf 0 :?> _
